theme: jekyll-theme-minimal
title: <div class="hello-world__pre-container"><pre class="hello-world__pre"><code>ğŸ ğŸ‡
  ğŸ˜€ ğŸ”¤Hello World!ğŸ”¤â—ï¸
ğŸ‰</code></pre></div>
description: Sara Shoujaa's CV
